workflows:
  ios-release:
    name: iOS TestFlight Release
    working_directory: flutter_app
    environment:
      flutter: "3.35.5"
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_CHANNEL: "stable"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.niya-y.testapp"
        APP_STORE_CONNECT_TEAM_ID: "F9HD79X8WM"

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Fetch & apply signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles --archive-method app-store

      - name: Build iOS for release
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --dart-define=ENV=prod

    artifacts:
      - flutter_app/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true

