workflows:
  ios-release:
    name: iOS TestFlight Release
    working_directory: flutter_app
    environment:
      flutter: "3.35.5"
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_CHANNEL: "stable"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.niya-y.testapp"   # 🔧 본인 Bundle ID
        APP_STORE_CONNECT_TEAM_ID: "F9HD79X8WM"  # 🔧 본인 Team ID

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      # 🔑 1. 서명 파일 먼저 세팅
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id $BUNDLE_ID \
            --create
          keychain add-certificates
          xcode-project use-profiles --archive-method app-store

      # 🔑 2. 이제 빌드 (서명된 상태로 IPA 생성)
      - name: Build iOS for release
        script: |
          flutter build ipa --release \
            --dart-define=ENV=prod

    artifacts:
      - flutter_app/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
