workflows:
  ios-release:
    name: iOS TestFlight Release
    environment:
      vars:
        FLUTTER_CHANNEL: "stable"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.niya-y.testapp" # <-- ðŸ”§ ì—¬ê¸°ë¥¼ ë³¸ì¸ ì•±ì˜ Bundle IDë¡œ ë³€ê²½
        APP_STORE_CONNECT_TEAM_ID: "F9HD79X8WM" # <-- ðŸ”§ ì—¬ê¸°ë¥¼ ë³¸ì¸ Apple Team IDë¡œ ë³€ê²½
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS for release
        script: |
          flutter build ipa --release --no-codesign \
            --dart-define=ENV=prod
      - name: Code signing
        script: |
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id $BUNDLE_ID \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --workspace $XCODE_WORKSPACE \
            --scheme $XCODE_SCHEME
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Codemagic Environmentì— ë“±ë¡
        submit_to_testflight: true
